version: '1'
services:
  docde:
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: my-app
    env_file:
      - .env
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    image: multiverse22/docde:latest
