version: '3'
services:
  docde:
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: my-app
    env_file:
      - .env
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    image: multiverse22/docde:latest
    volumes:
      - ./truststore.p12:/etc/ssl/certs/truststore.p12
    command: sh -c "update-ca-certificates && java -jar /app/myapp.jar"
