version: '3'
services:
  docde:
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: my-app
    env_file:
      - .env
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Djavax.net.ssl.trustStore=/usr/local/openjdk-17/lib/security/cacerts -Djavax.net.ssl.trustStorePassword=changeit

    image: multiverse22/docde:latest

