services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"