# 1. JDK 이미지 선택 (예: OpenJDK 17)
FROM openjdk:17-alpine

RUN apk update && apk add --no-cache ca-certificates

# 2. JAR 파일 복사
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
COPY ./ca.crt /tmp/ca.crt

RUN keytool -importcert -file /tmp/ca.crt -keystore /tmp/truststore.p12 -storetype PKCS12 -alias "ca" -noprompt -storepass changeit
RUN cp /tmp/truststore.p12 /etc/ssl/certs/truststore.p12



ENV SPRING_PROFILES_ACTIVE=prod

# 3. JAR 파일 실행
ENTRYPOINT ["java", "-jar", "/app.jar"]
