name: Deploy to EC2

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     
     - name: Log in to Docker Hub
       uses: docker/login-action@v3.3.0
       with:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
         
     - uses: appleboy/ssh-action@master
       with:
        key: ${{ secrets.EC2_SSH_KEY }} # 내가 변수로 저장한 pem key
        host: ${{secrets.AWS_INSTANCE_IP}} # 내가 변수로 저장한 ip
        username: ${{secrets.USER}} # 내가 변수로 저장한 User
        port: 22
        script: |
          echo "Creating .env file..."
          echo "SECRET_API_KEY=${{ secrets.SECRET_API_KEY }}" > /path/to/your/project/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> /path/to/your/project/.env
          # 필요한 다른 환경 변수를 추가할 수 있습니다
          echo ".env file created successfully"

          
        
        

        
