name: CI/CD 



on:
  pull_request:
    branches: [ "develop" ]

jobs:
  push_dockerhub:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
      run: |
        sudo apt-get update && sudo apt-get install -y awscli
        aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
        aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
        aws configure list
        aws s3 ls


    
