name: S3 TEST



on:
  pull_request:
    branches: [ "develop" ]

jobs:
  push_dockerhub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
      run: |
        sudo apt-get update && sudo apt-get install -y awscli
        aws configure set default.region "ap-northeast-2"
        aws configure list
        aws s3 cp s3://${{secrets.S3_BUCKET_NAME}}/ca/ca.crt ./ca.crt --debug
        ls -a

    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
        AWS_REGION: ap-northeast-2
      run: |
        aws autoscaling start-instance-refresh \
        --auto-scaling-group-name test \
        --cli-input-json file://instance-refresh-config.json


    
